# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.32
# 

Name:       dht

# >> macros
# << macros
%define keepstatic 1

Summary:    an implementation of DHT
Version:    0.25
Release:    0
Group:      Applications/Internet
License:    BSD
URL:        http://miniupnp.tuxfamily.org/
Source0:    %{name}-%{version}.tar.gz
Source100:  dht.yaml
Source101:  dht-rpmlintrc
Patch0:     dht-libdir-fix.patch
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig
BuildRequires:  cmake

%description
%{name} implements the variant of the Kademlia Distributed Hash Table (DHT)
used in the Bittorrent network

%if "%{?vendor}" == "chum"
PackageName: DHT
Type: console-application
PackagerName: nephros
DeveloperName: Juliusz Chroboczek
Custom:
  Repo: https://github.com/nephros/transmission
Url:
  Homepage: %{url}
  Help: http://miniupnp.tuxfamily.org/forum/
  Bugtracker: https://github.com/miniupnp/miniupnp/issues
%endif


%package devel
Summary:    Development files for %{name}
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}

%description devel
%{name} implements the variant of the Kademlia Distributed Hash Table (DHT)
used in the Bittorrent network

%if "%{?vendor}" == "chum"
PackageName: DHT
PackagerName: nephros
DeveloperName: Juliusz Chroboczek
Custom:
  Repo: https://github.com/nephros/transmission
Url:
  Homepage: %{url}
  Help: http://miniupnp.tuxfamily.org/forum/
  Bugtracker: https://github.com/miniupnp/miniupnp/issues
%endif


%prep
%setup -q -n %{name}-%{version}/%{name}

# dht-libdir-fix.patch
%patch0 -p1
# >> setup
# << setup

%build
# >> build pre
# << build pre

%cmake .  \
    -DUPNPC_BUILD_STATIC=FALSE \
    -DUPNPC_BUILD_TESTS=FALSE

make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post

%post -p /sbin/ldconfig

%postun -p /sbin/ldconfig

%files
%defattr(-,root,root,-)
# >> files
#%{_libdir}/*.so.*
# << files

%files devel
%defattr(-,root,root,-)
# >> files devel
%{_libdir}/*.a
%{_includedir}/*'
# << files devel
