# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.32
# 

Name:       miniupnpc

# >> macros
# << macros

Summary:    miniupnpc
Version:    2.0.20170509
Release:    0
Group:      Applications/Internet
License:    GPLv2+ and GPLv3+
URL:        https://transmissionbt.com
Source0:    %{name}-%{version}.tar.gz
Source100:  miniupnpc.yaml
Source101:  miniupnpc-rpmlintrc
Requires(post): systemd
Requires(postun): systemd
BuildRequires:  pkgconfig(openssl)
BuildRequires:  pkgconfig(libsystemd)
BuildRequires:  cmake
BuildRequires:  libevent-devel
BuildRequires:  libnatpmp-devel
BuildRequires:  curl-devel

%description
%{summary}.

%prep
%setup -q -n %{name}-%{version}/%{name}

# >> setup
# << setup

%build
# >> build pre
# << build pre


make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post

%files
%defattr(-,root,root,-)
%{_bindir}/*
%dir %{_datadir}/%{name}
%{_datadir}/%{name}/translations/*.qm
%{_datadir}/%{name}/qml/*
# >> files
# << files
