# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.32
# 

Name:       transmission

# >> macros
# << macros

Summary:    BitTorrent daemon and client
Version:    3.0.0
Release:    0
Group:      Applications/Internet
License:    GPLv2+ and GPLv3+
URL:        https://transmissionbt.com
Source0:    %{name}-%{version}.tar.gz
Source100:  transmission.yaml
Source101:  transmission-rpmlintrc
Patch0:     cmake-unused-command-line.patch
Patch1:     transmission-3.00-openssl-3.patch
Requires(post): systemd
Requires(postun): systemd
BuildRequires:  pkgconfig(openssl)
BuildRequires:  pkgconfig(libsystemd)
BuildRequires:  cmake
BuildRequires:  libevent-devel
BuildRequires:  libnatpmp-devel
BuildRequires:  curl-devel

%description
Transmission is a fast, easy, and free BitTorrent client.

%if "%{?vendor}" == "chum"
PackageName: Transmission
Type: console-application
PackagerName: nephros
Custom:
  Repo: https://github.com/nephros/transmission
Icon: %{url}/master/icons/template.svg
Url:
  Homepage:  https://transmissionbt.com
  Help: https://forum.transmissionbt.com/
  Bugtracker: https://github.com/transmission/transmission
  Donations:
    - https://noyb.eu/en/donations-other-support-options
    - https://my.fsfe.org/donate
    - https://supporters.eff.org/donate/join-4
    - https://openrepos.net/donate
%endif


%package daemon
Summary:    Daemon component of %{name}
Group:      Applications/Internet
Requires:   %{name} = %{version}-%{release}

%description daemon
Transmission is a fast, easy, and free BitTorrent client.

This is the headless daemon component.
%if "%{?vendor}" == "chum"
PackageName: Transmission Daemon
Type: console-application
PackagerName: nephros
%endif


%package cli
Summary:    CLI utility component of %{name}
Group:      Applications/Internet
Requires:   %{name} = %{version}-%{release}

%description cli
Transmission is a fast, easy, and free BitTorrent client.

This is the commmand-line utility component.
%if "%{?vendor}" == "chum"
PackageName: Transmission CLI
Type: console-application
PackagerName: nephros
%endif


%prep
%setup -q -n %{name}-%{version}/upstream

# cmake-unused-command-line.patch
%patch0 -p1
# transmission-3.00-openssl-3.patch
%patch1 -p1
# >> setup
# << setup

%build
# >> build pre
# << build pre

%cmake .  \
    -DCMAKE_INSTALL_DOCDIR=share/doc/%{name} \
    -DENABLE_CLI=ON \
    -DENABLE_GTK=OFF \
    -DENABLE_LIGHTWEIGHT=ON \
    -DENABLE_NLS=OFF \
    -DENABLE_QT=OFF \
    -DENABLE_TESTS=OFF \
    -DUSE_SYSTEM_EVENT2=ON \
    -DUSE_SYSTEM_DHT=OFF \
    -DUSE_SYSTEM_MINIUPNPC=OFF \
    -DUSE_SYSTEM_NATPMP=ON \
    -DUSE_SYSTEM_UTP=OFF \
    -DUSE_SYSTEM_B64=OFF \
    -DWITH_CRYPTO=openssl \
    -DWITH_INOTIFY=ON \
    -DWITH_LIBAPPINDICATOR=ON \
    -DWITH_SYSTEMD=ON

make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# mangle version info
sed -i -e "s/unreleased/%{version}/" %{buildroot}%{_datadir}/%{name}/qml/%{name}.qml
# << install post

%files
%defattr(-,root,root,-)
%{_bindir}/*
%dir %{_datadir}/%{name}
%{_datadir}/%{name}/translations/*.qm
%{_datadir}/%{name}/qml/*
# >> files
# << files

%files daemon
%defattr(-,root,root,-)
# >> files daemon
# << files daemon

%files cli
%defattr(-,root,root,-)
# >> files cli
# << files cli
