# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.32
# 

Name:       transmission

# >> macros
# << macros

Summary:    BitTorrent daemon and client
Version:    3.0.0
Release:    0
Group:      Applications/Internet
License:    GPLv2+ and GPLv3+
URL:        https://transmissionbt.com
Source0:    %{name}-%{version}.tar.gz
Source100:  transmission.yaml
Source101:  transmission-rpmlintrc
Requires(post): systemd
Requires(postun): systemd
BuildRequires:  pkgconfig(ssl)
BuildRequires:  systemd
BuildRequires:  qt5-qttools-linguist
BuildRequires:  qt5-qmake
BuildRequires:  qml-rpm-macros
BuildRequires:  libevent-devel
BuildRequires:  libnatpmp-devel
BuildRequires:  miniupnpc-devel
BuildRequires:  curl-devel

%description


%if "%{?vendor}" == "chum"
PackageName: Transmission
Type: console-application
PackagerName: nephros
Custom:
  Repo: https://github.com/nephros/transmission
Icon: %{url}/master/icons/template.svg
Url:
  Homepage:  https://transmissionbt.com
  Help: https://forum.transmissionbt.com/
  Bugtracker: https://github.com/transmission/transmission
  Donations:
    - https://noyb.eu/en/donations-other-support-options
    - https://my.fsfe.org/donate
    - https://supporters.eff.org/donate/join-4
    - https://openrepos.net/donate
%endif


%package daemon
Summary:    Daemon component of %{name}
Group:      Applications/Internet
Requires:   %{name} = %{version}-%{release}

%description daemon
%{summary}.

%package cli
Summary:    CLI utility component of %{name}
Group:      Applications/Internet
Requires:   %{name} = %{version}-%{release}

%description cli
%{summary}.

%prep
%setup -q -n %{name}-%{version}/upstream

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qmake5 

make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake5_install

# >> install post
# mangle version info
sed -i -e "s/unreleased/%{version}/" %{buildroot}%{_datadir}/%{name}/qml/%{name}.qml
# << install post

%files
%defattr(-,root,root,-)
%{_bindir}/*
%dir %{_datadir}/%{name}
%{_datadir}/%{name}/translations/*.qm
%{_datadir}/%{name}/qml/*
# >> files
# << files

%files daemon
%defattr(-,root,root,-)
# >> files daemon
# << files daemon

%files cli
%defattr(-,root,root,-)
# >> files cli
# << files cli
