# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.32
# 

Name:       transmission

# >> macros
# << macros

Summary:    BitTorrent daemon and client
Version:    3.0.0
Release:    0
Group:      Applications/Internet
License:    GPLv2+ or GPLv3+
URL:        https://transmissionbt.com
Source0:    %{name}-%{version}.tar.gz
Source1:    transmission-daemon.service
Source100:  transmission.yaml
Source101:  transmission-rpmlintrc
Patch0:     cmake-unused-command-line.patch
Patch1:     transmission-3.00-openssl-3.patch
Requires:   %{name}-daemon
Requires:   %{name}-cli
Requires:   %{name}-web
Requires:   %{name}-remote
Requires:   %{name}-tools
BuildRequires:  pkgconfig(openssl)
BuildRequires:  pkgconfig(systemd)
BuildRequires:  pkgconfig(libevent)
BuildRequires:  cmake
BuildRequires:  libnatpmp-devel
BuildRequires:  miniupnpc-devel
BuildRequires:  dht-devel
BuildRequires:  curl-devel

%description
Transmission is a fast, easy, and free BitTorrent client.

This package will install all components of Transmission.
If you only want the daemon or the remote, install the individual packages.

%if "%{?vendor}" == "chum"
PackageName: Transmission
Type: console-application
PackagerName: nephros
Categories:
 - Network
 - P2P
Custom:
  Repo: https://github.com/nephros/transmission
Icon: %{url}/assets/images/Transmission_icon.png
Url:
  Homepage:  https://transmissionbt.com
  Help: https://forum.transmissionbt.com/
  Bugtracker: https://github.com/transmission/transmission
  Donations:
    - https://noyb.eu/en/donations-other-support-options
    - https://my.fsfe.org/donate
    - https://supporters.eff.org/donate/join-4
    - https://openrepos.net/donate
%endif


%package daemon
Summary:    Daemon component of %{name}
Group:      Applications/Internet
Requires:   systemd
Requires(pre): systemd
Requires(post): systemd
Requires(postun): systemd

%description daemon
Transmission is a fast, easy, and free BitTorrent client.

This is the headless daemon component.
%if "%{?vendor}" == "chum"
PackageName: Transmission Daemon
Icon: %{url}/assets/images/Transmission_icon.png
Type: console-application
PackagerName: nephros
Categories:
 - Network
 - P2P
%endif


%package cli
Summary:    CLI utilities of %{name}
Group:      Applications/Internet

%description cli
Transmission is a fast, easy, and free BitTorrent client.

This is the commmand-line utility.
%if "%{?vendor}" == "chum"
PackageName: Transmission CLI
Icon: %{url}/assets/images/Transmission_icon.png
Type: console-application
PackagerName: nephros
Categories:
 - Network
 - P2P
%endif


%package web
Summary:    Web interface of %{name}
Group:      Applications/Internet
Requires:   %{name}-daemon

%description web
Transmission is a fast, easy, and free BitTorrent client.

This is the web interface component.
%if "%{?vendor}" == "chum"
PackageName: Transmission Web
Icon: %{url}/assets/images/Transmission_icon.png
Type: addon
PackagerName: nephros
Categories:
 - Network
 - P2P
%endif


%package remote
Summary:    Remote control CLI tool of %{name}
Group:      Applications/Internet

%description remote
Transmission is a fast, easy, and free BitTorrent client.

This is the commmand-line remote control utility.
%if "%{?vendor}" == "chum"
PackageName: Transmission Remote
Icon: %{url}/assets/images/Transmission_icon.png
Type: console-application
PackagerName: nephros
Categories:
 - Network
 - P2P
%endif


%package tools
Summary:    CLI tools of %{name}
Group:      Applications/Internet

%description tools
Transmission is a fast, easy, and free BitTorrent client.

This is the commmand-line utilities.
%if "%{?vendor}" == "chum"
PackageName: Transmission Tools
Icon: %{url}/assets/images/Transmission_icon.png
Type: console-application
PackagerName: nephros
Categories:
 - Network
 - P2P
%endif


%prep
%setup -q -n %{name}-%{version}/upstream

# cmake-unused-command-line.patch
%patch0 -p1
# transmission-3.00-openssl-3.patch
%patch1 -p1
# >> setup
# << setup

%build
# >> build pre
# << build pre

%cmake .  \
    -DCMAKE_INSTALL_DOCDIR=share/doc/%{name} \
    -DENABLE_CLI=ON \
    -DENABLE_GTK=OFF \
    -DENABLE_LIGHTWEIGHT=ON \
    -DENABLE_NLS=OFF \
    -DENABLE_QT=OFF \
    -DENABLE_TESTS=OFF \
    -DUSE_SYSTEM_EVENT2=ON \
    -DUSE_SYSTEM_DHT=ON \
    -DUSE_SYSTEM_MINIUPNPC=ON \
    -DUSE_SYSTEM_NATPMP=ON \
    -DUSE_SYSTEM_UTP=OFF \
    -DUSE_SYSTEM_B64=OFF \
    -DWITH_CRYPTO=openssl \
    -DWITH_INOTIFY=ON \
    -DWITH_LIBAPPINDICATOR=OFF \
    -DWITH_SYSTEMD=ON

make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# we don't need to install docs:
rm -rf %{buildroot}/%{_mandir}/*
rm -rf %{buildroot}/%{_docdir}/*
install -m644 -D %SOURCE1 %{buildroot}/%{_userunitdir}/%{name}-daemon.service
# << install post

%preun daemon
# >> preun daemon
%systemd_user_preun %{name}-daemon.service
# << preun daemon

%post daemon
# >> post daemon
%systemd_user_post %{name}-daemon.service
# << post daemon

%postun daemon
# >> postun daemon
%systemd_user_postun %{name}-daemon.service
# << postun daemon

%files
%defattr(-,root,root,-)
# >> files
# << files

%files daemon
%defattr(-,root,root,-)
%{_bindir}/%{name}-daemon
%{_userunitdir}/%{name}-daemon.service
# >> files daemon
# << files daemon

%files cli
%defattr(-,root,root,-)
%{_bindir}/%{name}-cli
# >> files cli
# << files cli

%files web
%defattr(-,root,root,-)
%dir %{_datadir}/%{name}/web
%{_datadir}/%{name}/web/*
# >> files web
# << files web

%files remote
%defattr(-,root,root,-)
%{_bindir}/%{name}-remote
# >> files remote
# << files remote

%files tools
%defattr(-,root,root,-)
%{_bindir}/%{name}-create
%{_bindir}/%{name}-edit
%{_bindir}/%{name}-show
# >> files tools
# << files tools
